apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-hub
  labels:
    app.kubernetes.io/name: ui-hub
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ui-hub
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ui-hub
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: ui-hub
        image: invisiblelife/ui-hub:latest
        
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        # Server configuration
        - name: SERVER_IP
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: SERVER_IP
        # External ports for building public URLs
        - name: EXTERNAL_SUPABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: service-endpoints
              key: EXTERNAL_SUPABASE_KONG_PORT
        - name: EXTERNAL_API_PORT
          valueFrom:
            configMapKeyRef:
              name: service-endpoints
              key: EXTERNAL_API_PORT
        # Build public URLs from IP and ports
        - name: VITE_SUPABASE_URL
          value: "http://$(SERVER_IP):$(EXTERNAL_SUPABASE_PORT)"
        - name: VITE_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: ANON_KEY
        - name: VITE_API_URL
          value: "http://$(SERVER_IP):$(EXTERNAL_API_PORT)"
        # Nginx proxy configuration
        - name: API_HOST
          value: "invisible-api"
        - name: API_PORT
          value: "4300"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi