apiVersion: v1
kind: Service
metadata:
  name: ui-hub
  labels:
    app.kubernetes.io/name: ui-hub
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: ui-hub
    app.kubernetes.io/component: frontend