# This patch adds Docker Hub authentication to all deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-used
spec:
  template:
    spec:
      imagePullSecrets:
      - name: dockerhub-secret