apiVersion: apps/v1
kind: Deployment
metadata:
  name: invisible-api
  labels:
    app.kubernetes.io/name: invisible-api
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: invisible-api
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: invisible-api
        app.kubernetes.io/component: api
    spec:
      containers:
      - name: api
        image: invisiblelife/api:latest
        ports:
        - containerPort: 4300
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4300"
        - name: IS_DOCKER
          value: "true"
        # Database
        - name: POSTGRES_URL
          value: "postgresql://postgres:$(POSTGRES_PASSWORD)@supabase-db:5432/postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        # Supabase
        - name: NEXT_PUBLIC_SUPABASE_URL
          value: "http://supabase-kong:8000"
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: ANON_KEY
        - name: SUPABASE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: JWT_SECRET
        # Service URLs
        - name: ETL_SERVICE_URL
          value: "http://invisible-etl:4001"
        - name: APP_BASE_URL
          value: "http://ui-hub"
        # Security
        - name: CREDENTIALS_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CREDENTIALS_ENCRYPTION_KEY
        - name: ENCRYPTION_ALGORITHM
          value: "aes-256-gcm"
        livenessProbe:
          httpGet:
            path: /health
            port: 4300
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4300
          initialDelaySeconds: 5
          periodSeconds: 5