apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: invisible
  name: invisible-api-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]  # For restart functionality