apiVersion: v1
kind: Service
metadata:
  name: invisible-api
  labels:
    app.kubernetes.io/name: invisible-api
    app.kubernetes.io/component: api
spec:
  type: NodePort
  ports:
  - port: 4300
    targetPort: 4300
    nodePort: 30084
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: invisible-api
    app.kubernetes.io/component: api