apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-meta
  namespace: invisible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-meta
  template:
    metadata:
      labels:
        app: supabase-meta
    spec:
      containers:
      - name: meta
        image: supabase/postgres-meta:v0.83.2
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PG_META_PORT
          value: "8080"
        - name: PG_META_DB_HOST
          value: "supabase-db"
        - name: PG_META_DB_PORT
          value: "5432"
        - name: PG_META_DB_NAME
          value: "postgres"
        - name: PG_META_DB_USER
          value: "postgres"
        - name: PG_META_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"