apiVersion: v1
kind: Service
metadata:
  name: supabase-meta
  namespace: invisible
spec:
  selector:
    app: supabase-meta
  ports:
  - port: 8080
    targetPort: 8080
    name: http
    protocol: TCP
  type: ClusterIP