apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invisible

resources:
  - hub/
  - chat/

commonLabels:
  app.kubernetes.io/part-of: invisible-platform
  app.kubernetes.io/managed-by: argocd