apiVersion: v1
kind: Service
metadata:
  name: invisible-operations
  labels:
    app.kubernetes.io/name: invisible-operations
    app.kubernetes.io/component: operations
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: invisible-operations
    app.kubernetes.io/component: operations