apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-postgres
  labels:
    app.kubernetes.io/name: supabase-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase-postgres
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase-postgres
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: supabase
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        
        imagePullPolicy: Always
        command: ['sh', '-c', 'chown -R 105:106 /var/lib/postgresql/data && chmod 700 /var/lib/postgresql/data']
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: supabase/postgres:15.8.1.060
        
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data
        - name: PGPORT
          value: "5432"
        - name: POSTGRES_PORT
          value: "5432"
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        - name: PGDATABASE
          value: postgres
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: JWT_SECRET
        - name: JWT_EXP
          value: "3600"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data