apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invisible

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

commonLabels:
  app.kubernetes.io/part-of: supabase