apiVersion: v1
kind: Service
metadata:
  name: supabase-db
  labels:
    app.kubernetes.io/name: supabase-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: supabase
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app.kubernetes.io/name: supabase-postgres