apiVersion: apps/v1
kind: Deployment
metadata:
  name: invisible-schema
  labels:
    app.kubernetes.io/name: invisible-schema
    app.kubernetes.io/component: schema
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: invisible-schema
      app.kubernetes.io/component: schema
  template:
    metadata:
      labels:
        app.kubernetes.io/name: invisible-schema
        app.kubernetes.io/component: schema
    spec:
      initContainers:
      # Wait for ETL to be ready
      - name: wait-for-etl
        image: busybox:1.35
        
        imagePullPolicy: Always
        command: ['sh', '-c', 'until nc -z invisible-etl 4001; do echo "Waiting for ETL..."; sleep 2; done; echo "ETL is ready"']
      containers:
      - name: schema
        image: invisiblelife/schema:latest
        
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: 
        - |
          echo "Running database migrations..."
          cd /app
          python scripts/migrations.py
          sqlmesh migrate
          sqlmesh plan --auto-apply
          echo "Migrations complete. Exiting."
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: SKIP_SQLMESH_UI
          value: "true"
        - name: POSTGRES_HOST
          value: "supabase-db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DATABASE
          value: "postgres"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi