apiVersion: apps/v1
kind: Deployment
metadata:
  name: invisible-schema
  labels:
    app.kubernetes.io/name: invisible-schema
    app.kubernetes.io/component: schema
spec:
  replicas: 1
  revisionHistoryLimit: 2  # Keep only 2 old replica sets for rollback
  selector:
    matchLabels:
      app.kubernetes.io/name: invisible-schema
      app.kubernetes.io/component: schema
  template:
    metadata:
      labels:
        app.kubernetes.io/name: invisible-schema
        app.kubernetes.io/component: schema
    spec:
      initContainers:
      # Wait for ETL to be ready
      - name: wait-for-etl
        image: busybox:1.35
        
        imagePullPolicy: Always
        command: ['sh', '-c', 'until nc -z invisible-etl 4001; do echo "Waiting for ETL..."; sleep 2; done; echo "ETL is ready"']
      containers:
      - name: schema
        image: invisiblelife/schema:latest
        
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: POSTGRES_HOST
          value: "supabase-db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DATABASE
          value: "postgres"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "test -f /proc/1/cmdline || exit 1"
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "test -f /proc/1/cmdline || exit 1"
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi