apiVersion: batch/v1
kind: Job
metadata:
  name: invisible-schema-migrate
  labels:
    app.kubernetes.io/name: invisible-schema
    app.kubernetes.io/component: schema
spec:
  ttlSecondsAfterFinished: 300  # Clean up job after 5 minutes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: invisible-schema
        app.kubernetes.io/component: schema
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: dockerhub-secret
      initContainers:
      # Wait for ETL to be ready
      - name: wait-for-etl
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z invisible-etl 4001; do echo "Waiting for ETL..."; sleep 2; done; echo "ETL is ready"']
      containers:
      - name: schema
        image: invisiblelife/schema:latest
        command: ["/bin/sh", "-c"]
        args: 
        - |
          echo "Running database migrations..."
          cd /app
          export DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}"
          echo "Database URL: postgresql://${POSTGRES_USER}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}"
          python scripts/migrations.py
          sqlmesh migrate
          sqlmesh plan --auto-apply
          echo "Migrations complete. Exiting."
        env:
        - name: POSTGRES_HOST
          value: "supabase-db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DATABASE
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi