apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml
  # - deployment.yaml  # Commented out - using Job instead
  # - service.yaml     # Not needed for migration job