apiVersion: v1
kind: Service
metadata:
  name: supabase-studio
  namespace: invisible
spec:
  selector:
    app: supabase-studio
  ports:
  - port: 3000
    targetPort: 3000
    name: http
    protocol: TCP
  type: ClusterIP