apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
      app.kubernetes.io/component: llm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
        app.kubernetes.io/component: llm
    spec:
      initContainers:
      - name: pull-models
        image: ollama/ollama:latest
        command: 
        - sh
        - -c
        - |
          ollama serve &
          sleep 5
          ollama pull deepseek-r1:8b || true
          ollama pull llama3.2:3b || true
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
      containers:
      - name: ollama
        image: ollama/ollama:latest
        
        imagePullPolicy: Always
        ports:
        - containerPort: 11434
          name: http
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        livenessProbe:
          httpGet:
            path: /
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            cpu: 2000m
            memory: 12Gi
          limits:
            cpu: 4000m
            memory: 16Gi
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data