apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: llm
spec:
  replicas: 1
  revisionHistoryLimit: 2  # Keep only 2 old replica sets for rollback
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
      app.kubernetes.io/component: llm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
        app.kubernetes.io/component: llm
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/part-of: invisible-platform
        environment: production
    spec:
      initContainers:
      - name: pull-models
        image: ollama/ollama:latest
        command: 
        - sh
        - -c
        - |
          ollama serve &
          sleep 5
          ollama pull deepseek-r1:8b || true
          ollama pull llama3.2:3b || true
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
      containers:
      - name: ollama
        image: ollama/ollama:latest
        
        imagePullPolicy: Always
        ports:
        - containerPort: 11434
          name: http
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        - name: OLLAMA_DEBUG
          value: "1"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        livenessProbe:
          httpGet:
            path: /
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            cpu: 8000m     # 8 CPU cores for better performance
            memory: 20Gi   # 20GB RAM for larger models and faster inference
          limits:
            cpu: 16000m    # Allow bursting to 16 cores
            memory: 40Gi   # Max 40GB RAM for heavy workloads
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-data