apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    consumers:
    - username: anon
      keyauth_credentials:
      - key: ${ANON_KEY}
    - username: service_role
      keyauth_credentials:
      - key: ${SERVICE_ROLE_KEY}

    services:
    - name: auth-v1-open
      url: http://supabase-auth:9999/verify
      routes:
      - name: auth-v1-open
        strip_path: true
        paths:
        - /auth/v1/verify
      plugins:
      - name: cors

    - name: auth-v1-open-callback
      url: http://supabase-auth:9999/callback
      routes:
      - name: auth-v1-open-callback
        strip_path: true
        paths:
        - /auth/v1/callback
      plugins:
      - name: cors

    - name: auth-v1-open-authorize
      url: http://supabase-auth:9999/authorize
      routes:
      - name: auth-v1-open-authorize
        strip_path: true
        paths:
        - /auth/v1/authorize
      plugins:
      - name: cors

    - name: auth-v1-open-otp
      url: http://supabase-auth:9999/otp
      routes:
      - name: auth-v1-open-otp
        strip_path: true
        paths:
        - /auth/v1/otp
      plugins:
      - name: cors

    - name: auth-v1-open-factors
      url: http://supabase-auth:9999/factors
      routes:
      - name: auth-v1-open-factors
        strip_path: true
        paths:
        - /auth/v1/factors
      plugins:
      - name: cors


    - name: auth-v1
      url: http://supabase-auth:9999/
      routes:
      - name: auth-v1-all
        strip_path: true
        paths:
        - /auth/v1/
      plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
          - anon
          - service_role

    - name: rest-v1
      url: http://supabase-rest:3000/
      routes:
      - name: rest-v1-all
        strip_path: false
        paths:
        - /rest/v1/
      plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: true
      - name: acl
        config:
          hide_groups_header: true
          allow:
          - anon
          - service_role

    - name: meta
      url: http://supabase-meta:8080/
      routes:
      - name: meta-all
        strip_path: true
        paths:
        - /pg/
      plugins:
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
          - service_role