apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    plugins:
    - name: cors
      config:
        origins:
        - "*"
        credentials: true
        headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
        - apikey
        - x-supabase-api-version
        - x-client-info
        methods:
        - GET
        - HEAD
        - PUT
        - PATCH
        - POST
        - DELETE
        - OPTIONS
        exposed_headers:
        - Authorization
        - Content-Type
        - apikey
        - x-supabase-api-version
        max_age: 3600
        preflight_continue: false

    consumers:
    - username: anon
      keyauth_credentials:
      - key: ${ANON_KEY}
      acls:
      - group: anon
    - username: service_role
      keyauth_credentials:
      - key: ${SERVICE_ROLE_KEY}
      acls:
      - group: service_role

    services:
    - name: auth-v1-open-verify
      url: http://supabase-auth:9999/verify
      routes:
      - name: auth-v1-open-verify
        strip_path: true
        paths:
        - /auth/v1/verify
      plugins:
      - name: cors
        config:
          origins:
          - "*"
          credentials: true
          preflight_continue: false
          headers:
          - Accept
          - Accept-Version
          - Content-Length
          - Content-MD5
          - Content-Type
          - Date
          - X-Auth-Token
          - Authorization
          - apikey
          - x-supabase-api-version
          - x-client-info
          methods:
          - GET
          - HEAD
          - PUT
          - PATCH
          - POST
          - DELETE
          - OPTIONS
          exposed_headers:
          - Authorization
          - Content-Type
          - apikey
          - x-supabase-api-version
          max_age: 3600

    - name: auth-v1-open-callback
      url: http://supabase-auth:9999/callback
      routes:
      - name: auth-v1-open-callback
        strip_path: true
        paths:
        - /auth/v1/callback
      plugins:
      - name: cors
        config:
          origins:
          - "*"
          credentials: true
          preflight_continue: false
          headers:
          - Accept
          - Accept-Version
          - Content-Length
          - Content-MD5
          - Content-Type
          - Date
          - X-Auth-Token
          - Authorization
          - apikey
          - x-supabase-api-version
          - x-client-info
          methods:
          - GET
          - HEAD
          - PUT
          - PATCH
          - POST
          - DELETE
          - OPTIONS
          exposed_headers:
          - Authorization
          - Content-Type
          - apikey
          - x-supabase-api-version
          max_age: 3600

    - name: auth-v1-open-authorize
      url: http://supabase-auth:9999/authorize
      routes:
      - name: auth-v1-open-authorize
        strip_path: true
        paths:
        - /auth/v1/authorize
      plugins:
      - name: cors
        config:
          origins:
          - "*"
          credentials: true
          preflight_continue: false
          headers:
          - Accept
          - Accept-Version
          - Content-Length
          - Content-MD5
          - Content-Type
          - Date
          - X-Auth-Token
          - Authorization
          - apikey
          - x-supabase-api-version
          - x-client-info
          methods:
          - GET
          - HEAD
          - PUT
          - PATCH
          - POST
          - DELETE
          - OPTIONS
          exposed_headers:
          - Authorization
          - Content-Type
          - apikey
          - x-supabase-api-version
          max_age: 3600

    - name: auth-v1-open-otp
      url: http://supabase-auth:9999
      routes:
      - name: auth-v1-open-otp
        strip_path: true
        paths:
        - /auth/v1
      plugins:
      - name: cors
        config:
          origins:
          - "*"
          credentials: true
          preflight_continue: false
          headers:
          - Accept
          - Accept-Version
          - Content-Length
          - Content-MD5
          - Content-Type
          - Date
          - X-Auth-Token
          - Authorization
          - apikey
          - x-supabase-api-version
          - x-client-info
          methods:
          - GET
          - HEAD
          - PUT
          - PATCH
          - POST
          - DELETE
          - OPTIONS
          exposed_headers:
          - Authorization
          - Content-Type
          - apikey
          - x-supabase-api-version
          max_age: 3600

    - name: auth-v1-factors
      url: http://supabase-auth:9999/factors
      routes:
      - name: auth-v1-factors
        strip_path: true
        paths:
        - /auth/v1/factors
      plugins:
      - name: cors
        config:
          origins:
          - "*"
          credentials: true
          preflight_continue: false
          headers:
          - Accept
          - Accept-Version
          - Content-Length
          - Content-MD5
          - Content-Type
          - Date
          - X-Auth-Token
          - Authorization
          - apikey
          - x-supabase-api-version
          - x-client-info
          methods:
          - GET
          - HEAD
          - PUT
          - PATCH
          - POST
          - DELETE
          - OPTIONS
          exposed_headers:
          - Authorization
          - Content-Type
          - apikey
          - x-supabase-api-version
          max_age: 3600
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
          - anon
          - service_role



    - name: auth-v1-user
      url: http://supabase-auth:9999/user
      routes:
      - name: auth-v1-user
        strip_path: true
        paths:
        - /auth/v1/user
      plugins:
      - name: cors
        config:
          origins:
          - "*"
          credentials: true
          preflight_continue: false
          headers:
          - Accept
          - Accept-Version
          - Content-Length
          - Content-MD5
          - Content-Type
          - Date
          - X-Auth-Token
          - Authorization
          - apikey
          - x-supabase-api-version
          - x-client-info
          methods:
          - GET
          - HEAD
          - PUT
          - PATCH
          - POST
          - DELETE
          - OPTIONS
          exposed_headers:
          - Authorization
          - Content-Type
          - apikey
          - x-supabase-api-version
          max_age: 3600
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow:
          - anon
          - service_role

