apiVersion: v1
kind: Service
metadata:
  name: supabase-kong
  labels:
    app.kubernetes.io/name: supabase-kong
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: supabase
spec:
  selector:
    app.kubernetes.io/name: supabase-kong
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: https
    port: 8443
    targetPort: 8443
    protocol: TCP
  type: ClusterIP