apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invisible-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: dockerhub-secret
  source:
    repoURL: https://github.com/invisible-life/deploy
    targetRevision: HEAD
    path: k8s/base/ui
  destination:
    server: https://kubernetes.default.svc
    namespace: invisible
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m