apiVersion: v1
kind: Service
metadata:
  name: mailpit
  labels:
    app.kubernetes.io/name: mailpit
    app.kubernetes.io/component: mail
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mailpit
    app.kubernetes.io/component: mail
  ports:
  - name: smtp
    port: 1025
    targetPort: 1025
    protocol: TCP
  - name: http
    port: 8025
    targetPort: 8025
    protocol: TCP