apiVersion: apps/v1
kind: Deployment
metadata:
  name: invisible-api
  namespace: invisible
spec:
  template:
    spec:
      containers:
      - name: api
        env:
        - name: API_PUBLIC_URL
          value: "http://136.243.50.116:4300"
        - name: SUPABASE_PUBLIC_URL
          value: "http://136.243.50.116:30082"