apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invisible

resources:
  - ../../base


# Production-specific patches
patches:
  # Set production resource limits
  - target:
      kind: Deployment
      name: invisible-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi

  - target:
      kind: Deployment
      name: invisible-etl
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi

  - target:
      kind: Deployment
      name: invisible-processor
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 4000m
            memory: 8Gi

  - target:
      kind: Deployment
      name: supabase-postgres
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 4000m
            memory: 8Gi

  - target:
      kind: Deployment
      name: supabase-kong
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi

  # Use specific image tags for production (these should be updated as part of CI/CD)
  - target:
      kind: Deployment
      name: invisible-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: invisiblelife/api:latest  # TODO: Replace with specific version

  - target:
      kind: Deployment
      name: invisible-etl
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: invisiblelife/etl:latest  # TODO: Replace with specific version

  - target:
      kind: Deployment
      name: invisible-processor
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: invisiblelife/processor:latest  # TODO: Replace with specific version

  - target:
      kind: Deployment
      name: invisible-schema
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: invisiblelife/schema:latest  # TODO: Replace with specific version

  - target:
      kind: Deployment
      name: invisible-operations
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: invisiblelife/operations:latest  # TODO: Replace with specific version

  - target:
      kind: Deployment
      name: ui-chat
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: invisiblelife/ui-chat:latest  # TODO: Replace with specific version

  - target:
      kind: Deployment
      name: ui-hub
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: invisiblelife/ui-hub:latest  # TODO: Replace with specific version

# Production ConfigMaps
configMapGenerator:
  - name: prod-config
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=warn
      - ENABLE_DEBUG=false
      - ENABLE_METRICS=true
      - ENABLE_TRACING=true

# Labels for production environment
commonLabels:
  environment: production

# Production-specific configurations
replicas:
  - name: invisible-api
    count: 1
  - name: invisible-etl
    count: 1
  - name: invisible-processor
    count: 1
  - name: supabase-kong
    count: 1