apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: invisible-platform
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - env: production
            namespace: invisible
            path: k8s/overlays/production
          - env: staging
            namespace: invisible-staging
            path: k8s/overlays/staging
      - list:
          elements:
          - cluster: in-cluster
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{env}}-invisible-platform'
    spec:
      project: default
      source:
        repoURL: https://github.com/invisible-life/deploy
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true