apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-auth
  labels:
    app.kubernetes.io/name: supabase-auth
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: supabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: supabase-auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: supabase-auth
        app.kubernetes.io/component: auth
        app.kubernetes.io/part-of: supabase
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        
        imagePullPolicy: Always
        command: ['sh', '-c', 'until nc -z supabase-db 5432; do echo "Waiting for database..."; sleep 2; done']
      - name: create-auth-schema
        image: postgres:15-alpine
        
        imagePullPolicy: Always
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        command: 
          - sh
          - -c
          - |
            psql -h supabase-db -U postgres -d postgres -c "CREATE SCHEMA IF NOT EXISTS auth;"
            psql -h supabase-db -U postgres -d postgres -c "GRANT ALL ON SCHEMA auth TO postgres;"
      containers:
      - name: auth
        image: supabase/gotrue:v2.158.1
        
        imagePullPolicy: Always
        ports:
        - containerPort: 9999
          name: http
        command:
          - sh
          - -c
          - |
            export DATABASE_URL="postgres://postgres:${POSTGRES_PASSWORD}@supabase-db:5432/postgres?search_path=auth"
            export GOTRUE_DB_DATABASE_URL="$DATABASE_URL"
            /usr/local/bin/auth
        env:
        # Database
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        - name: DB_NAMESPACE
          value: "auth"
        - name: DB_DRIVER
          value: "postgres"
        - name: GOTRUE_DB_DRIVER
          value: "postgres"
        
        # Auth settings
        - name: GOTRUE_API_HOST
          value: "0.0.0.0"
        - name: GOTRUE_API_PORT
          value: "9999"
        # Server configuration
        - name: SERVER_IP
          valueFrom:
            configMapKeyRef:
              name: server-config
              key: SERVER_IP
        # External ports
        - name: EXTERNAL_SUPABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: service-endpoints
              key: EXTERNAL_SUPABASE_KONG_PORT
        - name: EXTERNAL_UI_HUB_PORT
          valueFrom:
            configMapKeyRef:
              name: service-endpoints
              key: EXTERNAL_UI_HUB_PORT
        # Build public URLs from SERVER_IP and ports
        - name: API_EXTERNAL_URL
          value: "http://$(SERVER_IP):$(EXTERNAL_SUPABASE_PORT)"
        - name: GOTRUE_SITE_URL
          value: "http://$(SERVER_IP):$(EXTERNAL_UI_HUB_PORT)"
        
        # JWT - Extended session times
        - name: GOTRUE_JWT_EXP
          value: "259200"  # 3 days (72 hours)
        - name: GOTRUE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: JWT_SECRET
        - name: GOTRUE_JWT_DEFAULT_GROUP_NAME
          value: "authenticated"
        
        # Token expiry settings - Make tokens last much longer
        - name: GOTRUE_MAILER_OTP_EXP
          value: "3600"  # OTP/Magic link valid for 1 hour (3600 seconds)
        - name: GOTRUE_PASSWORD_MIN_LENGTH
          value: "6"
        - name: GOTRUE_SESSIONS_TIMEBOX
          value: "259200s"  # Session refresh timebox: 3 days (needs 's' suffix)
        - name: GOTRUE_SESSIONS_INACTIVITY_TIMEOUT
          value: "604800s"  # 7 days of inactivity before logout (needs 's' suffix)
        
        # Email (using Mailpit)
        - name: GOTRUE_SMTP_HOST
          value: "mailpit.invisible.svc.cluster.local"
        - name: GOTRUE_SMTP_PORT
          value: "1025"
        - name: GOTRUE_SMTP_USER
          value: ""
        - name: GOTRUE_SMTP_PASS
          value: ""
        - name: GOTRUE_SMTP_ADMIN_EMAIL
          value: "admin@invisible.life"
        - name: GOTRUE_MAILER_AUTOCONFIRM
          value: "true"
        - name: GOTRUE_MAILER_SECURE_EMAIL_CHANGE_ENABLED
          value: "false"
        - name: GOTRUE_SMTP_MAX_FREQUENCY
          value: "1s"
        
        # External providers (disabled)
        - name: GOTRUE_EXTERNAL_EMAIL_ENABLED
          value: "true"
        - name: GOTRUE_EXTERNAL_PHONE_ENABLED
          value: "false"
        
        # Rate limiting
        - name: GOTRUE_RATE_LIMIT_HEADER
          value: "X-Forwarded-For"
        - name: GOTRUE_RATE_LIMIT_EMAIL_SENT
          value: "3600"
        
        # CORS Configuration
        - name: GOTRUE_CORS_ALLOWED_ORIGINS
          value: "https://chat.kerman.ai,https://hub.kerman.ai,https://api.kerman.ai"
        - name: GOTRUE_CORS_ALLOWED_HEADERS
          value: "authorization,apikey,content-type,x-client-info,x-supabase-api-version"
        
        # MFA Configuration
        - name: GOTRUE_MFA_ENABLED
          value: "true"
        - name: GOTRUE_MFA_TOTP_ISSUER
          value: "Invisible"
        - name: GOTRUE_MFA_TOTP_ENABLED
          value: "true"
        - name: GOTRUE_MFA_MAX_ENROLLED_FACTORS
          value: "10"
        
        
        livenessProbe:
          httpGet:
            path: /health
            port: 9999
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9999
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi