apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invisible

resources:
  - ../../base
  - ingress.yaml


# Development-specific patches
patches:
  # Reduce resource requests for dev (but keep Kong higher)
  - target:
      kind: Deployment
      name: ".*"
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  
  # Kong needs more memory
  - target:
      kind: Deployment
      name: supabase-kong
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

  # Use latest tags for development
  - target:
      kind: Deployment
      name: invisible-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: invisiblelife/api:latest
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: API_PUBLIC_URL
          value: "http://localhost:8000/services/api"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SUPABASE_PUBLIC_URL
          value: "http://localhost:8000/api"
  
  - target:
      kind: Deployment
      name: invisible-etl
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: invisiblelife/etl:latest

  # Fix ui-hub environment variables for development
  - target:
      kind: Deployment
      name: ui-hub
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
        - name: VITE_SUPABASE_URL
          value: "http://localhost:8000/api"
        - name: VITE_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: ANON_KEY
        - name: VITE_API_URL
          value: "http://localhost:8000/services/api"


# Development ConfigMaps
configMapGenerator:
  - name: dev-config
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - ENABLE_DEBUG=true

# Labels for dev environment
commonLabels:
  environment: development