apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-hub
  namespace: invisible
spec:
  template:
    spec:
      initContainers:
      - name: fix-env-vars
        image: busybox:1.36
        command: 
        - sh
        - -c
        - |
          echo "Fixing environment variables in JavaScript..."
          
          # Copy original files
          cp -r /original-html/* /fixed-html/
          
          # Create environment config
          cat > /fixed-html/env.js << 'EOF'
          window.ENV = {
            VITE_SUPABASE_URL: 'http://localhost:8000/api',
            VITE_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzUzNDc2Njk2LCJleHAiOjE3ODUwMTI2OTZ9.mw3T0SbIczmTs9JIg0xS3JLsLlsn4ABtNLwtq90PRzM',
            VITE_API_URL: 'http://localhost:8000/services/api'
          };
          
          // Patch import.meta.env and process.env
          if (!window.import) window.import = {};
          if (!window.import.meta) window.import.meta = {};
          window.import.meta.env = window.ENV;
          
          if (!window.process) window.process = {};
          window.process.env = window.ENV;
          EOF
          
          # Update HTML to load env.js first
          sed -i 's|</head>|<script src="/env.js"></script></head>|' /fixed-html/index.html
          
          echo "Environment fix applied"
        volumeMounts:
        - name: original-html
          mountPath: /original-html
          readOnly: true
        - name: fixed-html
          mountPath: /fixed-html
      containers:
      - name: ui-hub
        volumeMounts:
        - name: fixed-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: original-html
        emptyDir: {}
      - name: fixed-html
        emptyDir: {}