apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-hub-config
  namespace: invisible
data:
  config.js: |
    window._env_ = {
      VITE_SUPABASE_URL: "http://localhost:8000/api",
      VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzUzNDc2Njk2LCJleHAiOjE3ODUwMTI2OTZ9.mw3T0SbIczmTs9JIg0xS3JLsLlsn4ABtNLwtq90PRzM",
      VITE_API_URL: "http://localhost:8000/services/api"
    };
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-hub
  namespace: invisible
spec:
  template:
    spec:
      volumes:
      - name: config
        configMap:
          name: ui-hub-config
      containers:
      - name: ui-hub
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js