apiVersion: v1
kind: Service
metadata:
  name: ui-chat
  labels:
    app.kubernetes.io/name: ui-chat
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: ui-chat
    app.kubernetes.io/component: frontend