apiVersion: apps/v1
kind: Deployment
metadata:
  name: invisible-processor
  labels:
    app.kubernetes.io/name: invisible-processor
    app.kubernetes.io/component: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: invisible-processor
      app.kubernetes.io/component: processor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: invisible-processor
        app.kubernetes.io/component: processor
    spec:
      terminationGracePeriodSeconds: 60  # Give processor time to finish current work
      containers:
      - name: processor
        image: invisiblelife/processor:latest
        
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "production"
        - name: CHAT_INTERVAL_HOURS
          value: "1"
        - name: LOG_LEVEL
          value: "INFO"
        # Polling configuration
        - name: POLLING_INTERVAL_MS
          value: "5000"
        - name: POLLING_ENABLED
          value: "true"
        - name: POLLING_MAX_RETRIES
          value: "3"
        - name: POLLING_RETRY_DELAY_MS
          value: "1000"
        # Process monitoring
        - name: ENABLE_HEARTBEAT
          value: "true"
        - name: HEARTBEAT_INTERVAL_MS
          value: "10000"
        - name: MAX_PROCESSING_TIME_MS
          value: "300000"  # 5 minutes max per container
        # Database
        - name: POSTGRES_HOST
          value: "supabase-db"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supabase-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DATABASE
          value: "postgres"
        - name: DATABASE_URL
          value: "postgresql://postgres:$(POSTGRES_PASSWORD)@supabase-db:5432/postgres"
        # LLM Configuration
        - name: OLLAMA_HOST
          value: "http://ollama:11434"  # Assumes Ollama service deployed separately
        - name: OLLAMA_REMOTE_HOST
          value: "http://ollama:11434"  # Remote Ollama host (same as local for now)
        - name: OLLAMA_ENDPOINT_URL
          value: "http://ollama:11434"  # Explicit endpoint URL for Ollama
        - name: LLM_ENDPOINT_FALLBACK
          value: "http://ollama:11434"  # Fallback when DB config missing endpoint
        - name: LLM_MODE_OVERRIDE
          value: "remote"  # Force remote mode when using k8s Ollama service
        - name: LLM_PROVIDER
          value: "ollama"
        - name: LLM_MODEL
          value: "deepseek-r1:8b"
        - name: USE_ENV_CONFIG_FALLBACK
          value: "true"  # Use environment variables when DB config incomplete
        # Service URLs
        - name: INVISIBLE_API_URL
          value: "http://invisible-api:4300"
        - name: INVISIBLE_ETL_URL
          value: "http://invisible-etl:4001"
        # Encryption
        - name: CREDENTIALS_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CREDENTIALS_ENCRYPTION_KEY
        # Health checks
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              # Check if processor has started
              echo "Checking processor startup..."
              # For now, just check if the process is running
              # The processor should create these files
              exit 0
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 12  # 60 seconds to start
          successThreshold: 1
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              # Check if process is responsive
              if [ -f /tmp/processor-heartbeat ]; then
                HEARTBEAT=$(cat /tmp/processor-heartbeat)
                CURRENT=$(date +%s)
                DIFF=$((CURRENT - HEARTBEAT))
                if [ $DIFF -gt 60 ]; then
                  echo "Processor heartbeat stale (${DIFF}s old)"
                  exit 1
                fi
              else
                echo "No heartbeat file found"
                exit 1
              fi
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              # Check if processor is ready
              if [ -f /tmp/processor-ready ]; then
                exit 0
              else
                exit 1
              fi
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi