apiVersion: v1
kind: Service
metadata:
  name: supabase-rest
  labels:
    app.kubernetes.io/name: supabase-rest
    app.kubernetes.io/component: postgrest
    app.kubernetes.io/part-of: supabase
spec:
  selector:
    app.kubernetes.io/name: supabase-rest
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP